name: movies_app
description: "movie diplom proweb app"
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.2.0-42.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.2
  meta: ^1.10.0
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  url_launcher: ^6.2.3
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  web: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
